import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronRight, FileText, Plus, Trash2 } from 'lucide-react'
import { api } from '../services/api'
import toast from '../utils/toast'

type Line = {
  key: string; product_id: string; product_type: string; decoration_method: string;
  description: string; artwork_id: string; qty: number; unit: string;
  unit_price: number; print_locations: string
}
const blankLine = (): Line => ({ key: crypto.randomUUID(), product_id:'', product_type:'', decoration_method:'DTF', description:'', artwork_id:'', qty:1, unit:'pcs', unit_price:0, print_locations:'' })

export function NewQuotationPage() {
  const { id } = useParams(); const navigate = useNavigate(); const qc = useQueryClient()
  const [form,setForm] = useState<any>({customer_id:'',lead_id:'',valid_until:'',status:'Draft',currency:'USD',discount_type:'percentage',discount_value:0,tax_percentage:0,shipping_amount:0,estimated_shipping_cost:0,notes:'',internal_notes:''})
  const [lines,setLines] = useState<Line[]>([blankLine()])
  const {data:customers=[]}=useQuery<any[]>({queryKey:['quote-customers'],queryFn:()=>api.get('/customers',{params:{limit:100}}).then(r=>r.data.data.rows)})
  const {data:leads=[]}=useQuery<any[]>({queryKey:['quote-leads'],queryFn:()=>api.get('/leads/list',{params:{limit:500}}).then(r=>r.data.data.rows)})
  const {data:artworks=[]}=useQuery<any[]>({queryKey:['quote-artworks'],queryFn:()=>api.get('/artworks',{params:{limit:200}}).then(r=>r.data.data.rows)})
  const {data:products=[]}=useQuery<any[]>({queryKey:['quote-products'],queryFn:()=>api.get('/products',{params:{limit:200}}).then(r=>r.data.data.rows)})
  const {data:existing}=useQuery<any>({queryKey:['quotation',id],queryFn:()=>api.get(`/quotations/${id}`).then(r=>r.data.data??r.data),enabled:!!id})

  useEffect(()=>{if(!existing)return;setForm({...form,...existing,customer_id:existing.customer_id??'',lead_id:existing.lead_id??'',discount_type:existing.discount_type??'percentage',discount_value:Number(existing.discount_value??existing.discount_pct??0),tax_percentage:Number(existing.tax_percentage??existing.tax_pct??0),shipping_amount:Number(existing.shipping_amount??0),estimated_shipping_cost:Number(existing.estimated_shipping??0)});setLines((existing.items??[]).map((x:any,i:number)=>({key:x.id??String(i),product_id:x.product_id??'',product_type:x.product_type??'',decoration_method:x.decoration_method??'',description:x.description??'',artwork_id:x.artwork_id??'',qty:Number(x.qty)||1,unit:x.unit??'pcs',unit_price:Number(x.unit_price)||0,print_locations:x.print_locations??''})))},[existing])

  const customer=customers.find(c=>c.id===form.customer_id)
  const amounts=useMemo(()=>{const items=lines.reduce((s,l)=>s+(Number(l.qty)||0)*(Number(l.unit_price)||0),0);const subtotal=items+(Number(form.shipping_amount)||0);const raw=form.discount_type==='fixed'?Number(form.discount_value)||0:subtotal*(Number(form.discount_value)||0)/100;const discount=Math.min(Math.max(raw,0),subtotal);const tax=(subtotal-discount)*(Number(form.tax_percentage)||0)/100;return{items,subtotal,discount,tax,total:subtotal-discount+tax}},[lines,form.shipping_amount,form.discount_type,form.discount_value,form.tax_percentage])
  const updateLine=(key:string,patch:Partial<Line>)=>setLines(v=>v.map(x=>x.key===key?{...x,...patch}:x))
  const mutation=useMutation({mutationFn:()=>{const payload={...form,customer_name:customer?.name??existing?.customer_name??null,company_name:customer?.company_name??customer?.company??null,billing_email:customer?.email??null,contact_number:customer?.mobile_number??customer?.company_phone_number??null,discount_value:Number(form.discount_value)||0,tax_percentage:Number(form.tax_percentage)||0,shipping_amount:Number(form.shipping_amount)||0,estimated_shipping_cost:Number(form.estimated_shipping_cost)||0,discount_pct:form.discount_type==='percentage'?Number(form.discount_value)||0:0,items:lines.filter(l=>l.description||l.product_type).map(({key,...l})=>({...l,product_id:l.product_id||null,artwork_id:l.artwork_id||null,qty:Number(l.qty),unit_price:Number(l.unit_price)}))};return id?api.put(`/quotations/${id}`,payload):api.post('/quotations',payload)},onSuccess:()=>{qc.invalidateQueries({queryKey:['quotations']});toast.success(id?'Quotation updated':'Quotation created');navigate('/quotations')},onError:(e:any)=>toast.error(e.response?.data?.message??'Unable to save quotation')})
  const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'})

  return <div className="nq-page">
    <header className="ncust-header"><div><div className="ns-breadcrumb"><span onClick={()=>navigate('/quotations')}>Quotations</span><ChevronRight size={13}/><strong>{id?'Edit':'New'} Quotation</strong></div><h2 className="ns-page-title">{id?'Edit':'New'} Quotation</h2></div><div className="ns-header-actions"><button className="lb-action-btn" onClick={()=>navigate(-1)}>Cancel</button><button className="lb-action-btn lb-action-primary" disabled={mutation.isPending||!form.customer_id||!lines.some(l=>l.description||l.product_type)} onClick={()=>mutation.mutate()}>{mutation.isPending?'Saving…':'Save Quotation'}</button></div></header>
    <section className="nq-card"><div className="nq-card-heading"><FileText size={16}/><h3>Quotation Details</h3></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14}}>
      <div className="al-field"><label>Customer *</label><select className="al-input" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.customer_no??c.customer_number} · {c.name}</option>)}</select></div>
      <div className="al-field"><label>Originating Lead</label><select className="al-input" value={form.lead_id} onChange={e=>setForm({...form,lead_id:e.target.value})}><option value="">No linked lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.lead_number} · {l.customer_name}</option>)}</select></div>
      <div className="al-field"><label>Valid Until</label><input className="al-input" type="date" value={form.valid_until??''} onChange={e=>setForm({...form,valid_until:e.target.value})}/></div>
      <div className="al-field"><label>Currency</label><select className="al-input" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option><option>CAD</option><option>EUR</option></select></div>
    </div></section>

    <section className="nq-card"><div className="nq-card-heading"><h3>Quotation Line Items</h3><button className="lb-action-btn" style={{marginLeft:'auto'}} onClick={()=>setLines(v=>[...v,blankLine()])}><Plus size={14}/> Add line</button></div>
      <div style={{overflowX:'auto'}}><table className="nq-table"><thead><tr><th>#</th><th>Catalog Product</th><th>Product Type</th><th>Decoration</th><th>Description</th><th>Artwork</th><th>Qty</th><th>Unit</th><th>Unit Price</th><th>Print Locations</th><th>Total</th><th/></tr></thead><tbody>{lines.map((l,i)=><tr key={l.key}>
        <td>{i+1}</td><td><select className="al-input" value={l.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value);updateLine(l.key,{product_id:e.target.value,product_type:p?.name??l.product_type})}}><option value="">Optional</option>{products.map(p=><option value={p.id} key={p.id}>{p.name??p.product_name}</option>)}</select></td>
        <td><input className="al-input" value={l.product_type} onChange={e=>updateLine(l.key,{product_type:e.target.value})} placeholder="DTF Transfer"/></td><td><input className="al-input" value={l.decoration_method} onChange={e=>updateLine(l.key,{decoration_method:e.target.value})}/></td><td><input className="al-input" value={l.description} onChange={e=>updateLine(l.key,{description:e.target.value})} placeholder="11x14 front"/></td>
        <td><select className="al-input" value={l.artwork_id} onChange={e=>updateLine(l.key,{artwork_id:e.target.value})}><option value="">None</option>{artworks.map(a=><option value={a.id} key={a.id}>{a.artwork_no} · {a.name}</option>)}</select></td>
        <td><input className="al-input" style={{width:75}} type="number" min="0.01" step="0.01" value={l.qty} onChange={e=>updateLine(l.key,{qty:+e.target.value})}/></td><td><select className="al-input" value={l.unit} onChange={e=>updateLine(l.key,{unit:e.target.value})}>{['pcs','inches','feet','sheets'].map(x=><option key={x}>{x}</option>)}</select></td>
        <td><input className="al-input" style={{width:100}} type="number" min="0" step="0.01" value={l.unit_price} onChange={e=>updateLine(l.key,{unit_price:+e.target.value})}/></td><td><input className="al-input" value={l.print_locations} onChange={e=>updateLine(l.key,{print_locations:e.target.value})} placeholder="Front, Back"/></td><td><strong>{money(l.qty*l.unit_price)}</strong></td><td><button className="nq-icon-btn" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter(x=>x.key!==l.key))}><Trash2 size={15}/></button></td>
      </tr>)}</tbody></table></div>
    </section>

    <div style={{display:'grid',gridTemplateColumns:'1fr 380px',gap:18}}><section className="nq-card"><div className="nq-card-heading"><h3>Notes</h3></div><div className="al-field"><label>Customer-facing Notes</label><textarea className="al-textarea" rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="al-field"><label>Internal Notes</label><textarea className="al-textarea" rows={4} value={form.internal_notes} onChange={e=>setForm({...form,internal_notes:e.target.value})}/></div></section>
    <section className="nq-card"><div className="nq-card-heading"><h3>Financial Summary</h3></div><div className="al-field"><label>Shipping Amount</label><input className="al-input" type="number" min="0" step="0.01" value={form.shipping_amount} onChange={e=>setForm({...form,shipping_amount:+e.target.value})}/></div><div className="al-field"><label>Estimated Shipping Cost (internal)</label><input className="al-input" type="number" min="0" step="0.01" value={form.estimated_shipping_cost} onChange={e=>setForm({...form,estimated_shipping_cost:+e.target.value})}/></div><div className="al-field-row"><div className="al-field"><label>Discount Type</label><select className="al-input" value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed</option></select></div><div className="al-field"><label>Discount Value</label><input className="al-input" type="number" min="0" step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:+e.target.value})}/></div></div><div className="al-field"><label>Tax Percentage</label><input className="al-input" type="number" min="0" max="100" step="0.01" value={form.tax_percentage} onChange={e=>setForm({...form,tax_percentage:+e.target.value})}/></div>
      <div style={{display:'grid',gap:7,marginTop:14,fontSize:13}}><span>Items <b style={{float:'right'}}>{money(amounts.items)}</b></span><span>Subtotal <b style={{float:'right'}}>{money(amounts.subtotal)}</b></span><span>Discount <b style={{float:'right'}}>-{money(amounts.discount)}</b></span><span>Tax <b style={{float:'right'}}>{money(amounts.tax)}</b></span><span style={{fontSize:17,borderTop:'1px solid #e2e8f0',paddingTop:10}}>Total <b style={{float:'right'}}>{money(amounts.total)}</b></span></div>
    </section></div>
  </div>
}
