-- 092_customer_contacts_and_fields.sql
-- Adds a people/contacts layer to the customer account, plus two missing
-- customer fields, per owner-approved audio requirements.
--
-- WHY (business): the `customers` row is the account / head office. A single
-- account (e.g. "Moutaz Mamlouk") can have many named people to deal with
-- (Purchasing, Accounts, Owner). Those people had nowhere to live. This table
-- gives them a home, linked back to the account.
--
-- Safety: additive + idempotent + nullable only. No existing column is changed,
-- no data is mutated, and no existing reader selects these new objects — so the
-- customer -> quotation -> invoice -> order -> PO conversion chain is unaffected.
-- (Those services select explicit customer columns; adding columns cannot shift
-- their positional INSERTs.)

-- 1) Contacts (people) belonging to a customer account -----------------------
CREATE TABLE IF NOT EXISTS customer_contacts (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_id   UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,  -- the account link
  first_name    VARCHAR(100),
  middle_name   VARCHAR(100),
  last_name     VARCHAR(100),
  job_title     VARCHAR(120),          -- role at the account (Purchasing, Accounts, Owner…)
  email         VARCHAR(255),
  phone         VARCHAR(50),
  mobile_number VARCHAR(50),
  whatsapp      VARCHAR(50),
  is_primary    BOOLEAN NOT NULL DEFAULT false,
  notes         TEXT,                  -- the customer's own contact notes (NOT internal_notes)
  created_by    UUID REFERENCES users(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ            -- soft delete, consistent with customers
);

-- FK index (every FK is indexed — Constitution §4.4)
CREATE INDEX IF NOT EXISTS idx_customer_contacts_customer ON customer_contacts(customer_id);

-- At most one primary contact per (non-deleted) account.
CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_contacts_one_primary
  ON customer_contacts(customer_id) WHERE is_primary AND deleted_at IS NULL;

-- 2) Two missing customer fields --------------------------------------------
-- Middle name (person-name split completed): first_name + middle_name + last_name.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100);

-- External customer number: a customer's id in a prior/external system.
-- Nullable and NOT unique on purpose — legacy values may be blank or collide,
-- and the internal `customer_number` (CUST####, generated by counter.js) stays
-- the authoritative unique id.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS external_customer_number VARCHAR(50);
CREATE INDEX IF NOT EXISTS idx_customers_external_number ON customers(external_customer_number);
