const express      = require('express')
const cors         = require('cors')
const helmet       = require('helmet')
const pinoHttp     = require('pino-http')
const cookieParser = require('cookie-parser')
const logger       = require('./utils/logger')
const errorHandler = require('./middleware/errorHandler')

const authRoutes    = require('./modules/auth/auth.routes')
const usersRoutes       = require('./modules/users/users.routes')
const permissionsRoutes = require('./modules/users/permissions.routes')
const supplierRoutes= require('./modules/suppliers/suppliers.routes')
const leadRoutes    = require('./modules/leads/leads.routes')
const quoteRoutes   = require('./modules/quotations/quotations.routes')
const orderRoutes   = require('./modules/orders/orders.routes')
const invoiceRoutes = require('./modules/invoices/invoices.routes')
const poRoutes      = require('./modules/purchase-orders/po.routes')
const shipRoutes    = require('./modules/shipments/shipments.routes')
const productRoutes = require('./modules/products/products.routes')
const artworkRoutes = require('./modules/artworks/artworks.routes')
const dashRoutes    = require('./modules/dashboard/dashboard.routes')
const supplierPortalRoutes = require('./modules/supplier-portal/portal.routes')
const customFieldRoutes    = require('./modules/custom-fields/custom_fields.routes')
const uploadRoutes         = require('./modules/upload/upload.routes')

const app = express()

app.use(helmet())
const allowedOrigins = (process.env.CORS_ORIGIN || '').split(',').map((o) => o.trim()).filter(Boolean)
app.use(cors({
  origin: (origin, cb) => {
    // No origin = curl / Postman / server-to-server — always allow
    if (!origin) return cb(null, true)
    // Any localhost origin is allowed (port 80 sends bare "http://localhost")
    if (/^https?:\/\/localhost(:\d+)?$/.test(origin)) return cb(null, true)
    if (allowedOrigins.includes(origin)) return cb(null, true)
    cb(new Error(`CORS: origin ${origin} not allowed`))
  },
  credentials: true,
}))
app.use(cookieParser())
app.use(express.json({ limit: '10mb' }))
app.use(pinoHttp({ logger }))
app.use('/uploads', express.static('uploads'))

app.use('/api/auth',           authRoutes)
app.use('/api/users',          usersRoutes)
app.use('/api/permissions',    permissionsRoutes)
app.use('/api/suppliers',      supplierRoutes)
app.use('/api/leads',          leadRoutes)
app.use('/api/quotations',     quoteRoutes)
app.use('/api/orders',         orderRoutes)
app.use('/api/invoices',       invoiceRoutes)
app.use('/api/purchase-orders',poRoutes)
app.use('/api/shipments',      shipRoutes)
app.use('/api/products',       productRoutes)
app.use('/api/artworks',       artworkRoutes)
app.use('/api/dashboard',      dashRoutes)
app.use('/api/supplier',       supplierPortalRoutes)
app.use('/api/custom-fields', customFieldRoutes)
app.use('/api/upload',       uploadRoutes)

app.use(errorHandler)

module.exports = app
