const express   = require('express')
const cors      = require('cors')
const helmet    = require('helmet')
const pinoHttp  = require('pino-http')
const logger    = require('./utils/logger')
const errorHandler = require('./middleware/errorHandler')

const authRoutes    = require('./modules/auth/auth.routes')
const usersRoutes       = require('./modules/users/users.routes')
const permissionsRoutes = require('./modules/users/permissions.routes')
const customerRoutes= require('./modules/customers/customers.routes')
const leadRoutes    = require('./modules/leads/leads.routes')
const quoteRoutes   = require('./modules/quotations/quotations.routes')
const orderRoutes   = require('./modules/orders/orders.routes')
const invoiceRoutes = require('./modules/invoices/invoices.routes')
const poRoutes      = require('./modules/purchase-orders/po.routes')
const shipRoutes    = require('./modules/shipments/shipments.routes')
const productRoutes = require('./modules/products/products.routes')
const artworkRoutes = require('./modules/artworks/artworks.routes')
const dashRoutes    = require('./modules/dashboard/dashboard.routes')

const app = express()

app.use(helmet())
app.use(cors({ origin: process.env.CORS_ORIGIN, credentials: true }))
app.use(express.json({ limit: '10mb' }))
app.use(pinoHttp({ logger }))
app.use('/uploads', express.static('uploads'))

app.use('/api/auth',           authRoutes)
app.use('/api/users',          usersRoutes)
app.use('/api/permissions',    permissionsRoutes)
app.use('/api/customers',      customerRoutes)
app.use('/api/leads',          leadRoutes)
app.use('/api/quotations',     quoteRoutes)
app.use('/api/orders',         orderRoutes)
app.use('/api/invoices',       invoiceRoutes)
app.use('/api/purchase-orders',poRoutes)
app.use('/api/shipments',      shipRoutes)
app.use('/api/products',       productRoutes)
app.use('/api/artworks',       artworkRoutes)
app.use('/api/dashboard',      dashRoutes)

app.use(errorHandler)

module.exports = app
